export const adminPortalSeed = {
  companies: [
    {
      id: "co_001",
      name: "Acme Health Group",
      ownerEmail: "owner@acmehealth.com",
      plan: "Enterprise",
      status: "Active",
      websites: 12,
      mrr: 1499,
      updated: "Today",
      suspension: { reason: "", notes: "", suspendedAt: null },
      usageLimits: { maxWebsites: 20, maxSeats: 50, monthlyPageViews: 1000000, storageGb: 500 },
      internalNotes: [
        { id: "note_001", text: "VIP account with dedicated success manager.", author: "Ops", createdAt: "2026-05-08" },
      ],
      websitesList: [
        { id: "ws_101", name: "acmehealth.com", title: "acmehealth.com", status: "Active", subtitle: "Primary production" },
        { id: "ws_102", name: "care.acmehealth.com", title: "care.acmehealth.com", status: "Active", subtitle: "Patient portal" },
      ],
      subscriptions: [{ id: "sub_101", title: "Enterprise Annual", status: "Active", subtitle: "Renews 2027-01-01" }],
      invoices: [
        { id: "inv_c101", title: "INV-101", status: "Paid", subtitle: "$1,499 - 2026-05-01" },
        { id: "inv_c102", title: "INV-102", status: "Pending", subtitle: "$1,499 - 2026-06-01" },
      ],
      auditEvents: [{ id: "evt_1001", title: "Usage limits updated", subtitle: "by Ava Rahman", updated: "Today" }],
    },
    {
      id: "co_002",
      name: "Northwind Agency",
      ownerEmail: "team@northwind.agency",
      plan: "Growth",
      status: "Trial",
      websites: 4,
      mrr: 349,
      updated: "Today",
      suspension: { reason: "", notes: "", suspendedAt: null },
      usageLimits: { maxWebsites: 8, maxSeats: 10, monthlyPageViews: 250000, storageGb: 100 },
      internalNotes: [],
      websitesList: [{ id: "ws_201", name: "northwind.agency", title: "northwind.agency", status: "Active", subtitle: "Marketing site" }],
      subscriptions: [{ id: "sub_201", title: "Growth Monthly", status: "Active", subtitle: "Renews 2026-06-08" }],
      invoices: [{ id: "inv_c201", title: "INV-201", status: "Pending", subtitle: "$349 - 2026-05-08" }],
      auditEvents: [],
    },
    {
      id: "co_003",
      name: "Bluebird Commerce",
      ownerEmail: "ops@bluebird.shop",
      plan: "Starter",
      status: "Past Due",
      websites: 2,
      mrr: 99,
      updated: "Yesterday",
      suspension: { reason: "", notes: "", suspendedAt: null },
      usageLimits: { maxWebsites: 3, maxSeats: 5, monthlyPageViews: 50000, storageGb: 20 },
      internalNotes: [{ id: "note_301", text: "Payment retries are active.", author: "Finance", createdAt: "2026-05-07" }],
      websitesList: [{ id: "ws_301", name: "bluebird.shop", title: "bluebird.shop", status: "Past Due", subtitle: "Billing lock risk" }],
      subscriptions: [{ id: "sub_301", title: "Starter Monthly", status: "Past Due", subtitle: "Renews 2026-05-01" }],
      invoices: [{ id: "inv_c301", title: "INV-301", status: "Overdue", subtitle: "$99 - 2026-04-28" }],
      auditEvents: [{ id: "evt_3001", title: "Dunning email sent", subtitle: "Finance Bot", updated: "Yesterday" }],
    },
  ],
  teamMembers: [
    { id: "tm_001", name: "Ava Rahman", email: "ava@pouchcare.com", role: "Owner", status: "Active", updated: "Today" },
    { id: "tm_002", name: "Mason Chow", email: "mason@pouchcare.com", role: "Support", status: "Active", updated: "Today" },
    { id: "tm_003", name: "Lina Park", email: "lina@pouchcare.com", role: "Finance", status: "Invited", updated: "Yesterday" },
  ],
  billingRecords: [
    { id: "inv_3001", company: "Acme Health Group", amount: 1499, status: "Paid", dueDate: "2026-05-01", updated: "Today" },
    { id: "inv_3002", company: "Northwind Agency", amount: 349, status: "Pending", dueDate: "2026-05-08", updated: "Today" },
    { id: "inv_3003", company: "Bluebird Commerce", amount: 99, status: "Overdue", dueDate: "2026-04-28", updated: "Yesterday" },
  ],
  leads: [
    { id: "ld_001", name: "John Carter", email: "john@example.com", company: "Carter & Co", source: "Contact Form", status: "New", assignedTo: "", priority: "High", updated: "Today" },
    { id: "ld_002", name: "Sara Lee", email: "sara@leedesign.com", company: "Lee Design Studio", source: "Landing Page", status: "Contacted", assignedTo: "Ava Rahman", priority: "Medium", updated: "Today" },
    { id: "ld_003", name: "Ali Khan", email: "ali@greenfield.org", company: "Greenfield NPO", source: "Referral", status: "Qualified", assignedTo: "Mason Chow", priority: "High", updated: "Yesterday" },
    { id: "ld_004", name: "Emily Chen", email: "emily@techstart.io", company: "TechStart Inc", source: "Demo Request", status: "New", assignedTo: "", priority: "Low", updated: "Yesterday" },
    { id: "ld_005", name: "David Park", email: "david@freshbites.com", company: "FreshBites", source: "Contact Form", status: "Converted", assignedTo: "Ava Rahman", priority: "Medium", updated: "3d ago" },
  ],
  platformSettings: {
    brandName: "PouchCare",
    supportEmail: "support@pouchcare.com",
    defaultTemplate: "saas-home",
    maintenanceMode: false,
    webhookUrl: "https://hooks.pouchcare.com/events",
    webhookSecret: "whsec_***",
    emailNotifications: true,
    slackIntegration: false,
    analyticsEnabled: true,
    customDomain: "app.pouchcare.com",
    maxUploadSizeMb: 50,
    allowedFileTypes: "jpg,png,svg,webp,pdf,mp4",
    privacyPolicyUrl: "https://pouchcare.com/privacy",
    termsUrl: "https://pouchcare.com/terms",
  },
  webhookLogs: [
    { id: "wh_001", event: "company.created", endpoint: "https://hooks.pouchcare.com/events", httpCode: 200, retryCount: 0, updated: "1h ago" },
    { id: "wh_002", event: "invoice.paid", endpoint: "https://hooks.pouchcare.com/events", httpCode: 200, retryCount: 0, updated: "3h ago" },
    { id: "wh_003", event: "subscription.renewed", endpoint: "https://hooks.pouchcare.com/events", httpCode: 502, retryCount: 2, updated: "Yesterday" },
  ],
  projects: [
    { id: "proj_001", name: "Acme Website Redesign", companyId: "co_001", companyName: "Acme Health Group", templateId: "tpl_005", templateName: "Clinic Home", status: "In Progress", assignedTo: "Ava Rahman", deadline: "2026-06-15", progress: 65, updated: "Today" },
    { id: "proj_002", name: "Northwind Agency Site", companyId: "co_002", companyName: "Northwind Agency", templateId: "tpl_009", templateName: "Agency Home", status: "Planning", assignedTo: "Mason Chow", deadline: "2026-07-01", progress: 15, updated: "Today" },
    { id: "proj_003", name: "Bluebird Store Launch", companyId: "co_003", companyName: "Bluebird Commerce", templateId: "tpl_013", templateName: "Ecommerce Home", status: "On Hold", assignedTo: "", deadline: "2026-08-01", progress: 0, updated: "Yesterday" },
  ],
  templates: [
    { id: "tpl_001", name: "SaaS Home", slug: "saas-home", category: "SaaS", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_002", name: "SaaS Pricing", slug: "saas-pricing", category: "SaaS", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_003", name: "SaaS Features", slug: "saas-features", category: "SaaS", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_004", name: "SaaS Contact", slug: "saas-contact", category: "SaaS", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_005", name: "Clinic Home", slug: "clinic-home", category: "Clinic", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_006", name: "Clinic Services", slug: "clinic-services", category: "Clinic", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_007", name: "Clinic Doctors", slug: "clinic-doctors", category: "Clinic", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_008", name: "Clinic Appointment", slug: "clinic-appointment", category: "Clinic", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_009", name: "Agency Home", slug: "agency-home", category: "Agency", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_010", name: "Agency Services", slug: "agency-services", category: "Agency", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_011", name: "Agency Portfolio", slug: "agency-portfolio", category: "Agency", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_012", name: "Agency Contact", slug: "agency-contact", category: "Agency", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_013", name: "Ecommerce Home", slug: "ecommerce-home", category: "Ecommerce", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_014", name: "Ecommerce Catalog", slug: "ecommerce-catalog", category: "Ecommerce", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_015", name: "Ecommerce Product Story", slug: "ecommerce-product-story", category: "Ecommerce", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_016", name: "Ecommerce Checkout Info", slug: "ecommerce-checkout-info", category: "Ecommerce", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_017", name: "Education Home", slug: "education-home", category: "Education", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_018", name: "Education Courses", slug: "education-courses", category: "Education", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_019", name: "Education Instructors", slug: "education-instructors", category: "Education", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_020", name: "Education Admissions", slug: "education-admissions", category: "Education", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_021", name: "Nonprofit Home", slug: "nonprofit-home", category: "Nonprofit", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_022", name: "Nonprofit Mission", slug: "nonprofit-mission", category: "Nonprofit", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_023", name: "Nonprofit Donate", slug: "nonprofit-donate", category: "Nonprofit", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
    { id: "tpl_024", name: "Nonprofit Events", slug: "nonprofit-events", category: "Nonprofit", status: "Active", type: "Page", version: "1.2.0", updated: "Today" },
  ],
  pages: [
    { id: "pg_001", title: "Home", slug: "/", template: "SaaS Home", status: "Published", seoScore: 92, updated: "Today" },
    { id: "pg_002", title: "Pricing", slug: "/pricing", template: "SaaS Pricing", status: "Published", seoScore: 88, updated: "Today" },
    { id: "pg_003", title: "Contact", slug: "/contact", template: "SaaS Contact", status: "Published", seoScore: 75, updated: "Yesterday" },
    { id: "pg_004", title: "About Us", slug: "/about", template: "None", status: "Draft", seoScore: 45, updated: "Yesterday" },
    { id: "pg_005", title: "Blog", slug: "/blog", template: "None", status: "Published", seoScore: 82, updated: "Today" },
  ],
  media: [
    { id: "md_001", name: "hero-banner.webp", type: "Image", size: "245 KB", dimensions: "1920x1080", alt: "Hero banner image", usageCount: 3, status: "Active", updated: "Today" },
    { id: "md_002", name: "logo.svg", type: "SVG", size: "12 KB", dimensions: "200x60", alt: "Company logo", usageCount: 8, status: "Active", updated: "Today" },
    { id: "md_003", name: "team-photo.jpg", type: "Image", size: "890 KB", dimensions: "2400x1600", alt: "Team photograph", usageCount: 1, status: "Active", updated: "Yesterday" },
    { id: "md_004", name: "product-demo.mp4", type: "Video", size: "15.2 MB", dimensions: "1920x1080", alt: "Product demo video", usageCount: 2, status: "Active", updated: "Yesterday" },
    { id: "md_005", name: "whitepaper.pdf", type: "Document", size: "2.1 MB", dimensions: "-", alt: "Q2 Whitepaper", usageCount: 1, status: "Active", updated: "3d ago" },
  ],
  seoEntries: [
    { id: "seo_001", pageTitle: "Home", slug: "/", metaTitle: "PouchCare - Build WordPress Sites Fast", metaDescription: "Professional WordPress website builder for agencies and businesses.", ogImage: "hero-banner.webp", schemaType: "WebSite", score: 92, status: "Optimized", updated: "Today" },
    { id: "seo_002", pageTitle: "Pricing", slug: "/pricing", metaTitle: "Plans & Pricing - PouchCare", metaDescription: "Choose the perfect plan for your business needs.", ogImage: "pricing-og.webp", schemaType: "Product", score: 88, status: "Optimized", updated: "Today" },
    { id: "seo_003", pageTitle: "Contact", slug: "/contact", metaTitle: "Contact Us - PouchCare", metaDescription: "", ogImage: "", schemaType: "ContactPage", score: 45, status: "Needs Work", updated: "Yesterday" },
    { id: "seo_004", pageTitle: "Blog", slug: "/blog", metaTitle: "Blog - PouchCare", metaDescription: "Latest articles and insights on web development.", ogImage: "blog-og.webp", schemaType: "Blog", score: 82, status: "Good", updated: "Today" },
    { id: "seo_005", pageTitle: "About Us", slug: "/about", metaTitle: "", metaDescription: "", ogImage: "", schemaType: "AboutPage", score: 20, status: "Missing", updated: "Yesterday" },
  ],
  activity: [
    { id: "aa_1", action: "Company upgraded to Enterprise", actor: "Ava Rahman", updated: "1h ago" },
    { id: "aa_2", action: "Invoice marked paid", actor: "Finance Bot", updated: "4h ago" },
  ],
  auditEvents: [{ id: "aud_1", action: "Seed initialized", actor: "System", target: "Portal", updated: "Today" }],
  notifications: [
    { id: "n1", title: "New company signup: Northwind Agency", level: "info", read: false, updated: "10m ago" },
    { id: "n2", title: "Payment received from Acme Health Group", level: "success", read: true, updated: "2h ago" },
  ],
};

