/** Must match `PERMISSION_KEYS` in apps/api/src/lib/managementPermissions.ts */
export const PERMISSION_KEYS = [
  'staff.branches',
  'staff.manage_profiles',
  'payroll.access',
  'finance.access',
  'finance.exchange_rates',
  'crm.client_accounts',
  'hr.recruitment',
  'hr.performance',
  'assets.devices',
  'monitor.view',
  'broadcast.access',
  'analytics.access',
  'admin_portal.access',
  'settings.role_permissions',
  // ── Admin Panel (clients/orders/services unified surface) ──
  'admin.overview.read',
  'admin.clients.read',
  'admin.clients.write',
  'admin.clients.wallet.adjust',
  'admin.clients.merge',
  'admin.orders.read',
  'admin.orders.write',
  'admin.orders.reassign',
  'admin.orders.refund',
  'admin.services.read',
  'admin.services.write',
  'admin.services.publish',
  'admin.services.pricing',
  'admin.billing.read',
  'admin.billing.approve',
  'admin.support.read',
  'admin.support.reply',
  'admin.support.close',
  'admin.assets.read',
  'admin.assets.write',
  'admin.broadcast.write',
  'admin.audit.read',
  'admin.settings.write',
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];
