import {
  LayoutDashboard,
  Building2,
  FolderKanban,
  LayoutTemplate,
  FileText,
  Image,
  Boxes,
  Layers,
  BarChart3,
  Store,
  Search,
  Inbox,
  Users,
  CreditCard,
  Settings,
  Activity,
  Mail,
  Server,
  UserCheck,
} from "lucide-react";

export const adminNav = [
  { label: "Dashboard", to: "/", icon: LayoutDashboard },
  { label: "Customers", to: "/customers", icon: UserCheck },
  { label: "Installations", to: "/installations", icon: Server },
  { label: "Companies", to: "/companies", icon: Building2 },
  { label: "Projects", to: "/projects", icon: FolderKanban },
  { label: "Templates", to: "/templates", icon: LayoutTemplate },
  { label: "Pages", to: "/pages", icon: FileText },
  { label: "Media", to: "/media", icon: Image },
  { label: "Blocks", to: "/blocks", icon: Boxes },
  { label: "Patterns", to: "/patterns", icon: Layers },
  { label: "Analytics", to: "/analytics", icon: BarChart3 },
  { label: "Marketplace", to: "/marketplace", icon: Store },
  { label: "SEO", to: "/seo", icon: Search },
  { label: "Leads", to: "/leads", icon: Inbox },
  { label: "Team", to: "/team", icon: Users },
  { label: "Billing", to: "/billing", icon: CreditCard },
  { label: "Settings", to: "/settings", icon: Settings },
  { label: "Emails", to: "/emails", icon: Mail },
  { label: "System", to: "/system", icon: Activity },
];
